# Gemfile
source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "webrick", "~> 1.7" # Required for serving Jekyll locally on Ruby 3.x
gem "jekyll-theme-minimal", "~> 0.2.0" # Ensure the theme is explicitly added
gem "csv" # Required due to Ruby 3.3 changes
gem "base64" # Add base64 to avoid warnings

