name: Release Workflow

on:
  release:
    types:
      - created

jobs:
  build-and-release:
    name: Build and Release Binaries
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            goos: linux
            goarch: amd64
          - os: macos-latest
            goos: darwin
            goarch: amd64
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.x

      - name: Build Binary
        run: |
          mkdir -p dist
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} \
          go build -o dist/goto-${{ matrix.goos }}-${{ matrix.goarch }} ./cmd/

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/goto-${{ matrix.goos }}-${{ matrix.goarch }}
          asset_name: goto-${{ matrix.goos }}-${{ matrix.goarch }}
          asset_content_type: application/octet-stream



          